### ISSUE TITLE
Are delays included?

### ISSUE THREAD

**Issue by carstenschwede** [pbock/fahrplan#8]
How does the software handle delayed trains? Is this kind of data provided via the API?

**Comment by pbock** [comment]
It doesn't, and the API doesn't provide any live data.

With that said, DB has released [a new API that _does_ provide delays](https://developer.deutschebahn.com/store/apis/info?name=Timetables&version=v1&provider=DBOpenData&), but it's entirely incompatible with [the previous API](https://developer.deutschebahn.com/store/apis/info?name=Fahrplan&version=v1&provider=DBOpenData&). It would be good to update the wrapper to be based on that API, but that would mean a full rewrite.

The new API is also an unappealing soup of unreadable XML along those lines:

```xml
<timetable station='Berlin Hbf'>
  <s id="3742440961287674842-1705141823-2">
    <tl f="F" t="p" o="80" c="ICE" n="542"/>
    <ar pt="1705141830" pp="14 A - D" hi="1" wings="-8488844539277976383-1705141823" ppth="Berlin Ostbahnhof"/>
    <dp pt="1705141833" pp="14 A - D" wings="-8488844539277976383-1705141823" ppth="Berlin-Spandau|Hannover Hbf|Bielefeld Hbf|Hamm(Westf)|Dortmund Hbf|Bochum Hbf|Essen Hbf|Duisburg Hbf|D&#252;sseldorf Flughafen|D&#252;sseldorf Hbf|K&#246;ln Hbf"/>
  </s>
  <!-- … -->
</timetable>
```

I'm not in much of a hurry to parse that.

What's more, the new API supports some features that the old API doesn't (like live data), but in turn doesn't seem to support some other features that the old API does (like full, detailed itineraries). I guess it would theoretically be possible to abstract all that away and build a hybrid wrapper for the two APIs combined, but I don't have the time or the patience for that at the moment.

**Comment by carstenschwede** [comment]
Thanks for the fast response.

**Comment by derhuerst** [comment]
To selfishly promote my own projects: [`db-hafas`](https://github.com/derhuerst/db-hafas) supports live data, but queries an unofficial API. I'm also in the process of bringing it up to date.
